name: CICD workflow for RC PoC

on:
  push:
    branches:
      - main
  
env:
  # REPO_S3_LOCATION_URI : "s3://amazon-sagemaker-891377342935-us-west-2-ak9r9o3k52qgeo/shared/repo/"
  DEV_S3_LOCATION_URI : "s3://amazon-sagemaker-891377342935-us-west-2-ak9r9o3k52qgeo/shared/dev/"
  BETA_S3_LOCATION_URI : "s3://amazon-sagemaker-891377342935-us-west-2-ak9r9o3k52qgeo/shared/beta/"
  GAMMA_S3_LOCATION_URI : "s3://amazon-sagemaker-891377342935-us-west-2-ak9r9o3k52qgeo/shared/gamma/"
  PROD_S3_LOCATION_URI : "s3://amazon-sagemaker-891377342935-us-west-2-ak9r9o3k52qgeo/shared/prod/"
  AWS_REGION : "us-east-1"
  ROLE_TO_ASSUME: "arn:aws:iam::891377342935:role/release-center-github-actions-poc-role"
  ROLE_TO_ASSUME_SESSION_NAME: "ReleaseCenterSession"
  
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  # upload-repo-to-s3:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Git clone the repository
  #       uses: actions/checkout@v4
        
  #     - name: Deploy repo to dev
  #       uses: ./.github/actions/deploy-util
  #       with:
  #         role-to-assume: ${{ env.ROLE_TO_ASSUME }}
  #         role-session-name: ${{ env.ROLE_TO_ASSUME_SESSION_NAME }}
  #         aws-region: ${{ env.AWS_REGION }}
  #         source: "."
  #         destination: ${{ env.REPO_S3_LOCATION_URI }}

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    # needs: upload-repo-to-s3
    steps:
      - uses: actions/checkout@v4
      - name: Deploy repo to dev
        uses: ./.github/actions/deploy-util
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_TO_ASSUME_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          source: "."
          destination: ${{ env.DEV_S3_LOCATION_URI }}

  deploy-beta:
    name: Deploy to Beta
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: approval-gate
    steps:
      - uses: actions/checkout@v4
      - name: Deploy repo to beta
        uses: ./.github/actions/deploy-util
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_TO_ASSUME_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          source: ${{ env.DEV_S3_LOCATION_URI }}
          destination: ${{ env.BETA_S3_LOCATION_URI }}


  deploy-gamma:
    name: Deploy to Gamma
    runs-on: ubuntu-latest
    needs: deploy-beta
    environment: approval-gate

    steps:
      - uses: actions/checkout@v4
      - name: Deploy repo to gamma
        uses: ./.github/actions/deploy-util
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_TO_ASSUME_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          source: ${{ env.BETA_S3_LOCATION_URI }}
          destination: ${{ env.GAMMA_S3_LOCATION_URI }}

          
  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-gamma
    environment: approval-gate
    steps:
      - uses: actions/checkout@v4
      - name: Deploy repo to dev
        uses: ./.github/actions/deploy-util
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_TO_ASSUME_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          source: ${{ env.GAMMA_S3_LOCATION_URI }}
          destination: ${{ env.PROD_S3_LOCATION_URI }}
